services:
  frontend:
    restart: always
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - 4200:80
      

  api:
    restart: always
    build:
      context: ../server
      dockerfile: Dockerfile
      target: production
    env_file:
      - ../server/.env
    ports:
      - 3000:3000
    depends_on:
      - mongoCont

  mongoCont:
    image: mongo
    restart: always
    env_file:
      - ../server/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-db:/data/db
    ports:
      - 27018:27017

volumes:
  mongo-db:
