services:
  frontend:
    restart: always
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - 4200:80

  mongoCont:
    image: mongo
    restart: always
    env_file:
      - ../server/.env
    volumes:
      - mongo-db:/data/db
    ports:
      - 27018:27017


  api:
    restart: always
    build:
      context: ../server
      dockerfile: Dockerfile
      target: production
    env_file:
      - ../server/.env
    ports:
      - 3000:3000
    extra_hosts:
      - "mongoservice:172.17.0.1"
    depends_on:
      - mongoCont


volumes:
  mongo-db:
