services:
  api:
    build:
      context: .
      target: production
    env_file:
      - .env
    ports:
      - 3000:3000
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-db:/data/db
    ports:
      - 27017:27017

volumes:
  mongo-db:
