

services:
  api:
    build:
      context: .
      target: production
    env_file:
      - .env
    ports:
      - 3000:3000
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-db:/data/db
    ports:
      - 27017:27017

volumes:
  mongo-db: