name: CICD

on:
  push:
    branches: [development]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      
      - name: Navigate to server directory
        working-directory: server
        run: ls
