name: CICD

on:
  push:
    branches: [development]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Update .env file
        working-directory: server
        run: |
          # Overwrite the .env file with the new content from ENV_VARIABLES secret
          echo "Overwriting .env file with new content from ENV_VARIABLES secret..."
          echo "${{ secrets.ENV_VARIABLES }}" > .env
          
      - name: Docker compose up
        working-directory: server
        run: sudo docker compose up -d --build
