name: CICD

on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t bsimhd/neuron-api ./server
      - name: Publish image to docker hub
        run: docker push bsimhd/neuron-api:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull bsimhd/neuron-api:latest
      - name: Delete old container
        run: sudo docker rm -f neuron-api
      - name: Run docker compose
        run: sudo docker compose -f ~/docker-compose.yaml up -d
